// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBm-tq04NvnFMKxUD51meUowvQ7AvNMeHg',
    appId: '1:152052145842:android:c3314dfe4e93a77b8333ab',
    messagingSenderId: '152052145842',
    projectId: 'goodlook-43438',
    storageBucket: 'goodlook-43438.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDV_Jpvgc5O_-kYqqLu5GVMPIj2Kv2Xrq8',
    appId: '1:152052145842:ios:661d1ed1412d646a8333ab',
    messagingSenderId: '152052145842',
    projectId: 'goodlook-43438',
    storageBucket: 'goodlook-43438.appspot.com',
    androidClientId:
        '152052145842-06dvg1m8lsgje89t4m95cs5urbue3r3e.apps.googleusercontent.com',
    iosClientId:
        '152052145842-j3b9lgrmrmjtma1bcbobhq2p4efp6c6o.apps.googleusercontent.com',
    iosBundleId: 'uz.goodlook.salon',
  );
}
